### PR TITLE
Add lauch jenkins server blog

### PR DESCRIPTION
**Pull request by resouer**
A blog to show how to run Jenkins on Hyper_

The publish date of this blog is not determined yet.

### CODE REVIEW

**Comment by jmknyc06** [comment]
My edits.

https://gist.github.com/jmknyc06/b4a0e479745169cc26aafc1271330456

**Comment by Gnep** [comment]
@resouer 

- Has @jmknyc06 's edit been merged?
- If done, @imeoer plz publish

**Comment by resouer** [comment]
@Gnep James' comment is not in, I will update develop branch.

**Comment by resouer** [comment]
@imeoer Now develop branch has been updated with James' comment, sorry for the mess.

**Comment by imeoer** [comment]
@resouer ok, will do that.

**Pull request merged**
